# Generated by Django 4.1 on 2023-04-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=500)),
                ('message', models.TextField()),
                ('from_mail', models.EmailField(max_length=254)),
                ('to_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
